### ISSUE TITLE
Short Your If Conditions & Remove useless vars

### ISSUE THREAD

**Issue by yassinrais** [melbahja/environ#2]
+ Remove duplicate return
+ Remove useless vars

```php
public static function get(string $k, $default = null)
{
	$val = $_ENV[$k] ?? getenv($k);

	if ($val === false) {
		return $default;
        }

	return $val;
}
```
to : 
```php
public static function get(string $k, $default = null)
{
	return ($_ENV[$k] ?? getenv($k)) ?: $default ;
}
```
---
```php
public static function set(string $k, $v): bool
{
	$_ENV[$k] = $v;

	if (is_string($v)) {
		return putenv("{$k}={$v}");
	}

	return true;
}
```
to : 
```php
public static function set(string $k, $v): bool
{
        $_ENV[$k] = $v;
	return is_string($_ENV[$k]) ? putenv("{$k}={$v}") : true ;
}
```

👍 🔢 ^^

**Comment by melbahja** [comment]
that short and cleaner, I will updated later today
thank you :+1:

**Comment by melbahja** [comment]
Get method that's a breaking change in case of:

```ini
VAR = false
```
get will return `null`, which is not the same value of `getenv('VAR')`

**Comment by yassinrais** [comment]
I was thinking about that , so 
i made  a test about getenv with ?? / ?: 

And i found that even diffirent machine (linux , windows)
have not same result ( i know its wired )

**Comment by melbahja** [comment]
is tests passed in windows? if not what the log ?

**Comment by yassinrais** [comment]
no , the test was about getenv return value 
not about environ class

**Comment by melbahja** [comment]
I've added some tests and passed in: `tests/EnvironTest.php`

is that what you mean or something else? and can you type your test code...

thanks

**Comment by melbahja** [comment]
I'm gonna merge, if you have any suggestions feel free to open a PR.
